version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: vibe-coding-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: vibechallenge
    volumes:
      - mongodb_data:/data/db
    networks:
      - vibe-coding-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vibe-coding-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/vibechallenge?authSource=admin
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      LOG_LEVEL: info
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - vibe-coding-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vibe-coding-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - vibe-coding-network

volumes:
  mongodb_data:

networks:
  vibe-coding-network:
    driver: bridge 